Option Strict On
Option Explicit On
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34003
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports Microsoft.VisualBasic.ApplicationServices

Namespace My

    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = False
            Me.EnableVisualStyles = True
            Me.SaveMySettingsOnExit = True
            Me.ShutdownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
        End Sub

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Protected Overrides Sub OnCreateMainForm()
            My.Application.ChangeUICulture("es")

            Dim Login As New FrmLogin
            Login.ShowDialog()

            If Login.DialogResult = DialogResult.OK Then
                Me.MainForm = Global.SysNominav3.frmMain
            Else
                End
            End If
        End Sub

        Private Sub MyApplication_Startup(sender As Object, e As StartupEventArgs) Handles Me.Startup
            'Comprobar Nueva Instancia del Servidor
            Dim NuevaInstancia As String = GetSetting("Simtesis", "SysNomina2014", "Server")
            '

            If NuevaInstancia.Trim.Length > 0 Then
                If NuevaInstancia.Trim = "192.168.0.2" Then SaveSetting("Simtesis", "SysNomina2014", "Server", "192.168.0.2\GRMSQL2014")
            End If
        End Sub
    End Class
End Namespace
